default:
  target: "{{ env_var('DBT_TARGET') }}"
  outputs:
    prod:
      type: postgres
      host: "{{ env_var('DBT_DB_HOST') }}"
      port: 5432
      user: "{{ env_var('DBT_DB_USER') }}"
      password: "{{ env_var('DBT_DB_PASSWORD') }}"
      dbname: "{{ env_var('DBT_DB_NAME') }}"
      schema: public
      threads: 1
